def main(arg):
    raise Exception(arg)