2009-08-21 23:01:57,755|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_8'}
2009-08-21 23:01:57,756|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:57,757|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:57,757|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_8'}
2009-08-21 23:01:57,791|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:57,791|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:57,792|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_9'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:57,794|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:57,794|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_9'}
2009-08-21 23:01:57,795|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:57,796|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:57,796|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_9'}
2009-08-21 23:01:57,830|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:57,831|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:57,831|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_9'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:57,834|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:57,835|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_9'}
2009-08-21 23:01:57,835|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:57,836|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:57,836|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_9'}
2009-08-21 23:01:57,872|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:57,873|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:57,873|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_9'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:57,874|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:57,875|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_9'}
2009-08-21 23:01:57,875|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:57,876|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:57,876|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_9'}
2009-08-21 23:01:57,912|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:57,912|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:57,912|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_10'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:57,915|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:57,915|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_10'}
2009-08-21 23:01:57,915|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:57,916|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:57,917|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_10'}
2009-08-21 23:01:57,952|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:57,952|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:57,952|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_10'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:57,953|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:57,954|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_10'}
2009-08-21 23:01:57,954|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:57,955|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:57,956|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_10'}
2009-08-21 23:01:57,990|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:57,991|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:57,991|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_10'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:57,994|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:57,994|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_10'}
2009-08-21 23:01:57,994|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:57,995|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:57,996|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_10'}
2009-08-21 23:01:58,030|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:58,031|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:58,031|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_11'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:58,033|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:58,034|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_11'}
2009-08-21 23:01:58,034|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:58,035|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:58,035|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_11'}
2009-08-21 23:01:58,071|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:58,071|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:58,071|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_11'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:58,074|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:58,074|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_11'}
2009-08-21 23:01:58,074|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:58,075|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:58,076|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_11'}
2009-08-21 23:01:58,112|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:58,112|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:58,112|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_11'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:58,115|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:58,115|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_11'}
2009-08-21 23:01:58,115|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:58,116|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:58,117|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_11'}
2009-08-21 23:01:58,152|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:58,152|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:58,153|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_12'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:58,155|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:58,155|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_12'}
2009-08-21 23:01:58,155|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:58,156|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:58,157|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_12'}
2009-08-21 23:01:58,190|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:58,191|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:58,191|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_12'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:58,194|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:58,194|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_12'}
2009-08-21 23:01:58,194|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:58,195|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:58,196|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_12'}
2009-08-21 23:01:58,231|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:58,232|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:58,232|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_12'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:58,235|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:58,235|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_12'}
2009-08-21 23:01:58,235|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:58,236|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:58,237|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_12'}
2009-08-21 23:01:58,270|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:58,271|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:58,271|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_13'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:58,274|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:58,274|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_13'}
2009-08-21 23:01:58,274|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:58,275|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:58,276|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_13'}
2009-08-21 23:01:58,311|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:58,311|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:58,311|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_13'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:58,313|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:58,314|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_13'}
2009-08-21 23:01:58,314|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:58,315|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:58,315|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_13'}
2009-08-21 23:01:58,352|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:58,352|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:58,352|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_13'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:58,355|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:58,355|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_13'}
2009-08-21 23:01:58,356|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:58,357|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:58,357|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_13'}
2009-08-21 23:01:58,391|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:58,391|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:58,392|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_14'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:58,395|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:58,395|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_14'}
2009-08-21 23:01:58,396|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:58,397|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:58,397|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_14'}
2009-08-21 23:01:58,430|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:58,431|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:58,431|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_14'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:58,434|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:58,434|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_14'}
2009-08-21 23:01:58,434|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:58,435|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:58,436|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_14'}
2009-08-21 23:01:58,472|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:58,472|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:58,472|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_14'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:58,474|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:58,475|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_14'}
2009-08-21 23:01:58,475|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:58,476|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:58,476|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_14'}
2009-08-21 23:01:58,511|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:58,512|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:58,512|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_15'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:58,515|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:58,516|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_15'}
2009-08-21 23:01:58,516|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:58,517|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:58,517|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_15'}
2009-08-21 23:01:58,550|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:58,551|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:58,551|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_15'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:58,554|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:58,554|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_15'}
2009-08-21 23:01:58,554|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:58,555|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:58,556|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_15'}
2009-08-21 23:01:58,592|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:58,592|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:58,592|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_15'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:58,595|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:58,596|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_15'}
2009-08-21 23:01:58,596|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:58,597|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:58,597|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_15'}
2009-08-21 23:01:58,631|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:58,632|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:58,632|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_16'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:58,639|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:58,640|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_16'}
2009-08-21 23:01:58,640|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:58,641|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:58,642|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_16'}
2009-08-21 23:01:58,672|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:58,672|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:58,672|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_16'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:58,683|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:58,683|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_16'}
2009-08-21 23:01:58,683|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:58,684|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:58,685|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_16'}
2009-08-21 23:01:58,710|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:58,711|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:58,711|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_16'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:58,727|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:58,727|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_16'}
2009-08-21 23:01:58,727|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:58,729|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:58,730|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_16'}
2009-08-21 23:01:58,750|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:58,751|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:58,751|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_17'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:58,767|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:58,767|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_17'}
2009-08-21 23:01:58,768|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:58,769|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:58,770|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_17'}
2009-08-21 23:01:58,791|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:58,791|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:58,791|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_17'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:58,807|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:58,807|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_17'}
2009-08-21 23:01:58,807|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:58,809|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:58,809|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_17'}
2009-08-21 23:01:58,831|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:58,832|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:58,832|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_17'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:58,846|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:58,846|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_17'}
2009-08-21 23:01:58,847|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:58,849|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:58,849|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_17'}
2009-08-21 23:01:58,872|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:58,872|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:58,872|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_18'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:58,887|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:58,887|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_18'}
2009-08-21 23:01:58,888|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:58,890|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:58,890|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_18'}
2009-08-21 23:01:58,913|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:58,914|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:58,914|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_18'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:58,930|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:58,931|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_18'}
2009-08-21 23:01:58,931|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:58,932|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:58,933|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_18'}
2009-08-21 23:01:58,955|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:58,955|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:58,956|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_18'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:58,971|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:58,972|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_18'}
2009-08-21 23:01:58,972|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:58,973|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:58,974|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_18'}
2009-08-21 23:01:58,995|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:58,996|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:58,996|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_19'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:59,014|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:59,015|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_19'}
2009-08-21 23:01:59,015|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:59,017|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:59,017|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_19'}
2009-08-21 23:01:59,035|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:59,035|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:59,036|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_19'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:59,055|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:59,055|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_19'}
2009-08-21 23:01:59,056|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:59,057|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:59,058|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_19'}
2009-08-21 23:01:59,075|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:59,076|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:59,076|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_19'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:59,098|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:59,099|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_19'}
2009-08-21 23:01:59,099|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:59,100|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:59,101|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_19'}
2009-08-21 23:01:59,115|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:59,115|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:59,116|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_20'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:59,142|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:59,143|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_20'}
2009-08-21 23:01:59,143|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:59,144|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:59,145|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_20'}
2009-08-21 23:01:59,155|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:59,155|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:59,155|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_20'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:59,184|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:59,184|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_20'}
2009-08-21 23:01:59,184|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:59,186|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:59,187|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_20'}
2009-08-21 23:01:59,195|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:59,195|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:59,195|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_20'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:59,227|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:59,227|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_20'}
2009-08-21 23:01:59,227|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:59,229|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:59,230|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_20'}
2009-08-21 23:01:59,236|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:59,236|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:59,236|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_21'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:59,267|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:59,267|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_21'}
2009-08-21 23:01:59,267|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:59,269|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:59,269|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_21'}
2009-08-21 23:01:59,274|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:59,275|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:59,275|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_21'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:59,311|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:59,311|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_21'}
2009-08-21 23:01:59,311|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:59,312|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:59,313|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_21'}
2009-08-21 23:01:59,315|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:59,315|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:59,315|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_21'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:59,351|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:59,351|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_21'}
2009-08-21 23:01:59,351|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:59,353|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:59,353|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_21'}
2009-08-21 23:01:59,355|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:59,355|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:59,356|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_22'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:59,394|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:59,396|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_22'}
2009-08-21 23:01:59,396|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:59,398|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:59,398|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_22'}
2009-08-21 23:01:59,399|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:59,399|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:59,399|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_22'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:59,437|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:59,438|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_22'}
2009-08-21 23:01:59,439|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:59,440|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:59,442|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_22'}
2009-08-21 23:01:59,442|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:59,442|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:59,442|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_22'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:59,480|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:59,481|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:59,481|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_22'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_23'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:59,482|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:59,483|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_22'}
2009-08-21 23:01:59,483|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:59,485|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:59,485|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_22'}
2009-08-21 23:01:59,519|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:59,520|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:59,520|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_23'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_23'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:59,523|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:59,524|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_23'}
2009-08-21 23:01:59,525|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:59,526|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:59,526|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_23'}
2009-08-21 23:01:59,560|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:59,560|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:59,560|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_23'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_23'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:59,566|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:59,567|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_23'}
2009-08-21 23:01:59,568|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:59,569|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:59,569|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_23'}
2009-08-21 23:01:59,599|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:59,600|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:59,600|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_23'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_24'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:59,611|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:59,611|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_23'}
2009-08-21 23:01:59,612|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:59,613|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:59,614|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_23'}
2009-08-21 23:01:59,639|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:59,639|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:59,639|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_24'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_24'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:59,654|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:59,654|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_24'}
2009-08-21 23:01:59,654|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:59,656|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:59,656|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_24'}
2009-08-21 23:01:59,678|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:59,679|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:59,679|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_24'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_24'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:59,694|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:59,694|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_24'}
2009-08-21 23:01:59,694|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:59,696|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:59,697|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_24'}
2009-08-21 23:01:59,718|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:59,718|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:59,719|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_24'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_25'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:59,735|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:59,735|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_24'}
2009-08-21 23:01:59,736|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:59,737|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:59,738|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_24'}
2009-08-21 23:01:59,764|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:59,764|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:59,765|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_25'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_25'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:59,775|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:59,775|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_25'}
2009-08-21 23:01:59,775|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:59,777|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:59,778|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_25'}
2009-08-21 23:01:59,803|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:59,803|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:59,804|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_25'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_25'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:59,819|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:59,820|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_25'}
2009-08-21 23:01:59,820|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:59,823|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:59,823|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_25'}
2009-08-21 23:01:59,844|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:59,844|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:59,844|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_25'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_26'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:59,865|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:59,866|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_25'}
2009-08-21 23:01:59,866|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:59,868|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:59,868|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_25'}
2009-08-21 23:01:59,883|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:59,883|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:59,883|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_26'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_26'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:59,907|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:59,907|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_26'}
2009-08-21 23:01:59,907|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:59,909|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:59,910|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_26'}
2009-08-21 23:01:59,924|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:59,925|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:59,925|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_26'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_26'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:59,946|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:59,946|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_26'}
2009-08-21 23:01:59,947|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:59,948|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:59,949|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_26'}
2009-08-21 23:01:59,963|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:01:59,964|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:01:59,964|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_26'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_27'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:01:59,986|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:01:59,986|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_26'}
2009-08-21 23:01:59,987|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:01:59,988|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:01:59,989|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_26'}
2009-08-21 23:02:00,003|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:00,004|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:00,004|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_27'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_27'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:00,026|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:00,027|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_27'}
2009-08-21 23:02:00,027|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:00,028|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:00,029|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_27'}
2009-08-21 23:02:00,043|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:00,043|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:00,043|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_27'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_27'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:00,067|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:00,067|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_27'}
2009-08-21 23:02:00,068|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:00,069|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:00,070|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_27'}
2009-08-21 23:02:00,083|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:00,084|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:00,084|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_27'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_28'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:00,107|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:00,107|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_27'}
2009-08-21 23:02:00,108|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:00,109|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:00,110|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_27'}
2009-08-21 23:02:00,123|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:00,123|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:00,124|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_28'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_28'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:00,151|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:00,151|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_28'}
2009-08-21 23:02:00,152|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:00,153|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:00,154|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_28'}
2009-08-21 23:02:00,162|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:00,163|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:00,163|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_28'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_28'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:00,193|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:00,194|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_28'}
2009-08-21 23:02:00,194|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:00,196|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:00,197|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_28'}
2009-08-21 23:02:00,204|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:00,204|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:00,204|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_28'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_29'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:00,235|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:00,236|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_28'}
2009-08-21 23:02:00,236|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:00,238|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:00,238|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_28'}
2009-08-21 23:02:00,243|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:00,244|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:00,244|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_29'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_29'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:00,279|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:00,280|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_29'}
2009-08-21 23:02:00,280|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:00,281|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:00,282|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_29'}
2009-08-21 23:02:00,283|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:00,284|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:00,284|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_29'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_29'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:00,318|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:00,318|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_29'}
2009-08-21 23:02:00,319|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:00,320|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:00,320|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_29'}
2009-08-21 23:02:00,323|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:00,324|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:00,324|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_29'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_30'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:00,359|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:00,359|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_29'}
2009-08-21 23:02:00,359|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:00,361|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:00,362|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_29'}
2009-08-21 23:02:00,366|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:00,367|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:00,367|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_30'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_30'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:00,398|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:00,398|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_30'}
2009-08-21 23:02:00,398|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:00,399|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:00,400|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_30'}
2009-08-21 23:02:00,407|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:00,407|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:00,408|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_30'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_30'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:00,438|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:00,438|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_30'}
2009-08-21 23:02:00,438|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:00,439|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:00,440|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_30'}
2009-08-21 23:02:00,447|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:00,448|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:00,448|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_30'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_31'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:00,479|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:00,480|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_30'}
2009-08-21 23:02:00,480|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:00,481|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:00,481|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_30'}
2009-08-21 23:02:00,488|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:00,489|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:00,490|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_31'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_31'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:00,519|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:00,520|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_31'}
2009-08-21 23:02:00,520|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:00,521|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:00,521|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_31'}
2009-08-21 23:02:00,528|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:00,528|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:00,528|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_31'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_31'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:00,558|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:00,558|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_31'}
2009-08-21 23:02:00,558|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:00,559|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:00,560|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_31'}
2009-08-21 23:02:00,567|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:00,568|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:00,568|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_31'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_32'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:00,599|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:00,600|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_31'}
2009-08-21 23:02:00,600|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:00,601|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:00,601|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_31'}
2009-08-21 23:02:00,606|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:00,607|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:00,607|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_32'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_32'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:00,638|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:00,638|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_32'}
2009-08-21 23:02:00,638|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:00,639|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:00,640|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_32'}
2009-08-21 23:02:00,647|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:00,647|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:00,648|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_32'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_32'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:00,679|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:00,679|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_32'}
2009-08-21 23:02:00,680|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:00,681|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:00,681|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_32'}
2009-08-21 23:02:00,687|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:00,688|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:00,688|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_32'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_33'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:00,719|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:00,719|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_32'}
2009-08-21 23:02:00,719|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:00,720|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:00,721|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_32'}
2009-08-21 23:02:00,727|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:00,727|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:00,727|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_33'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_33'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:00,758|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:00,758|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_33'}
2009-08-21 23:02:00,758|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:00,759|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:00,760|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_33'}
2009-08-21 23:02:00,767|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:00,768|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:00,768|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_33'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_33'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:00,799|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:00,799|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_33'}
2009-08-21 23:02:00,799|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:00,800|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:00,801|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_33'}
2009-08-21 23:02:00,807|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:00,808|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:00,808|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_33'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_34'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:00,839|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:00,839|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_33'}
2009-08-21 23:02:00,839|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:00,840|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:00,841|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_33'}
2009-08-21 23:02:00,847|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:00,847|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:00,848|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_34'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_34'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:00,879|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:00,879|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_34'}
2009-08-21 23:02:00,879|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:00,880|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:00,881|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_34'}
2009-08-21 23:02:00,887|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:00,887|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:00,887|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_34'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_34'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:00,918|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:00,918|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_34'}
2009-08-21 23:02:00,918|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:00,919|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:00,920|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_34'}
2009-08-21 23:02:00,926|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:00,926|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:00,926|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_34'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_35'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:00,959|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:00,959|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_34'}
2009-08-21 23:02:00,959|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:00,960|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:00,961|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_34'}
2009-08-21 23:02:00,967|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:00,968|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:00,968|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_35'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_35'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:00,999|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:00,999|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_35'}
2009-08-21 23:02:00,999|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:01,000|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:01,001|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_35'}
2009-08-21 23:02:01,007|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:01,008|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:01,008|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_35'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_35'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:01,039|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:01,039|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_35'}
2009-08-21 23:02:01,039|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:01,040|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:01,041|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_35'}
2009-08-21 23:02:01,047|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:01,047|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:01,048|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_35'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_36'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:01,078|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:01,079|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_35'}
2009-08-21 23:02:01,079|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:01,080|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:01,080|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_35'}
2009-08-21 23:02:01,087|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:01,087|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:01,087|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_36'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_36'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:01,118|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:01,118|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_36'}
2009-08-21 23:02:01,118|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:01,119|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:01,120|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_36'}
2009-08-21 23:02:01,128|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:01,128|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:01,128|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_36'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_36'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:01,159|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:01,159|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_36'}
2009-08-21 23:02:01,160|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:01,161|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:01,161|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_36'}
2009-08-21 23:02:01,167|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:01,168|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:01,168|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_36'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_37'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:01,198|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:01,198|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_36'}
2009-08-21 23:02:01,198|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:01,200|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:01,200|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_36'}
2009-08-21 23:02:01,206|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:01,207|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:01,207|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_37'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_37'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:01,239|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:01,239|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_37'}
2009-08-21 23:02:01,239|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:01,240|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:01,241|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_37'}
2009-08-21 23:02:01,246|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:01,246|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:01,247|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_37'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_37'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:01,279|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:01,279|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_37'}
2009-08-21 23:02:01,279|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:01,280|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:01,281|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_37'}
2009-08-21 23:02:01,286|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:01,287|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:01,287|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_37'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_38'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:01,318|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:01,318|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_37'}
2009-08-21 23:02:01,318|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:01,320|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:01,320|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_37'}
2009-08-21 23:02:01,328|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:01,328|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:01,328|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_38'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_38'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:01,357|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:01,358|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_38'}
2009-08-21 23:02:01,358|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:01,359|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:01,360|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_38'}
2009-08-21 23:02:01,367|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:01,368|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:01,368|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_38'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_38'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:01,398|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:01,398|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_38'}
2009-08-21 23:02:01,399|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:01,400|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:01,400|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_38'}
2009-08-21 23:02:01,407|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:01,408|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:01,408|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_38'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_39'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:01,438|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:01,438|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_38'}
2009-08-21 23:02:01,438|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:01,439|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:01,440|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_38'}
2009-08-21 23:02:01,447|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:01,447|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:01,447|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_39'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_39'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:01,478|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:01,478|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_39'}
2009-08-21 23:02:01,478|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:01,479|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:01,480|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_39'}
2009-08-21 23:02:01,488|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:01,488|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:01,488|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_39'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_39'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:01,519|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:01,520|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_39'}
2009-08-21 23:02:01,520|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:01,521|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:01,522|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_39'}
2009-08-21 23:02:01,527|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:01,527|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:01,528|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_39'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_40'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:01,558|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:01,558|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_39'}
2009-08-21 23:02:01,558|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:01,559|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:01,560|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_39'}
2009-08-21 23:02:01,567|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:01,567|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:01,567|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_40'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_40'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:01,599|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:01,600|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_40'}
2009-08-21 23:02:01,600|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:01,601|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:01,601|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_40'}
2009-08-21 23:02:01,607|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:01,607|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:01,607|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_40'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_40'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:01,639|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:01,639|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_40'}
2009-08-21 23:02:01,639|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:01,640|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:01,641|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_40'}
2009-08-21 23:02:01,647|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:01,647|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:01,647|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_40'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_41'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:01,679|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:01,680|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_40'}
2009-08-21 23:02:01,680|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:01,681|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:01,682|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_40'}
2009-08-21 23:02:01,687|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:01,688|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:01,688|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_41'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_41'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:01,718|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:01,718|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_41'}
2009-08-21 23:02:01,718|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:01,720|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:01,720|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_41'}
2009-08-21 23:02:01,727|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:01,728|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:01,728|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_41'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_41'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:01,759|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:01,759|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_41'}
2009-08-21 23:02:01,760|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:01,761|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:01,761|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_41'}
2009-08-21 23:02:01,767|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:01,767|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:01,767|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_41'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_42'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:01,799|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:01,800|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_41'}
2009-08-21 23:02:01,800|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:01,801|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:01,801|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_41'}
2009-08-21 23:02:01,807|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:01,808|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:01,808|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_42'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_42'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:01,838|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:01,838|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_42'}
2009-08-21 23:02:01,838|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:01,839|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:01,840|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_42'}
2009-08-21 23:02:01,846|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:01,847|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:01,847|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_42'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_42'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:01,879|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:01,879|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_42'}
2009-08-21 23:02:01,880|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:01,881|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:01,881|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_42'}
2009-08-21 23:02:01,887|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:01,888|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:01,888|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_42'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_43'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:01,919|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:01,919|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_42'}
2009-08-21 23:02:01,919|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:01,920|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:01,921|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_42'}
2009-08-21 23:02:01,927|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:01,928|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:01,928|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_43'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_43'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:01,959|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:01,959|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_43'}
2009-08-21 23:02:01,960|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:01,961|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:01,961|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_43'}
2009-08-21 23:02:01,968|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:01,968|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:01,968|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_43'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_43'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:01,999|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:01,999|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_43'}
2009-08-21 23:02:02,000|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:02,001|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:02,001|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_43'}
2009-08-21 23:02:02,008|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:02,008|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:02,008|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_43'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_44'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:02,038|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:02,038|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_43'}
2009-08-21 23:02:02,039|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:02,040|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:02,040|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_43'}
2009-08-21 23:02:02,046|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:02,047|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:02,047|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_44'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_44'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:02,079|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:02,079|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_44'}
2009-08-21 23:02:02,079|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:02,080|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:02,081|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_44'}
2009-08-21 23:02:02,087|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:02,087|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:02,088|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_44'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_44'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:02,118|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:02,118|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_44'}
2009-08-21 23:02:02,118|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:02,119|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:02,120|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_44'}
2009-08-21 23:02:02,126|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:02,126|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:02,126|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_44'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_45'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:02,159|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:02,160|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_44'}
2009-08-21 23:02:02,160|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:02,161|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:02,162|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_44'}
2009-08-21 23:02:02,167|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:02,167|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:02,168|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_45'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_45'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:02,198|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:02,198|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_45'}
2009-08-21 23:02:02,198|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:02,199|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:02,200|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_45'}
2009-08-21 23:02:02,206|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:02,206|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:02,207|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_45'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_45'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:02,238|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:02,238|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_45'}
2009-08-21 23:02:02,238|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:02,239|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:02,240|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_45'}
2009-08-21 23:02:02,246|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:02,247|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:02,247|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_45'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_46'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:02,278|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:02,278|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_45'}
2009-08-21 23:02:02,278|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:02,280|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:02,280|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_45'}
2009-08-21 23:02:02,288|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:02,288|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:02,288|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_46'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_46'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:02,319|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:02,319|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_46'}
2009-08-21 23:02:02,320|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:02,321|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:02,321|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_46'}
2009-08-21 23:02:02,327|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:02,327|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:02,327|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_46'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_46'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:02,360|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:02,361|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_46'}
2009-08-21 23:02:02,361|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:02,362|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:02,362|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_46'}
2009-08-21 23:02:02,367|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:02,368|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:02,368|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_46'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_47'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:02,402|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:02,402|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_46'}
2009-08-21 23:02:02,403|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:02,404|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:02,405|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_46'}
2009-08-21 23:02:02,406|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:02,406|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:02,406|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_47'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_47'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:02,443|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:02,443|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_47'}
2009-08-21 23:02:02,443|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:02,445|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:02,445|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_47'}
2009-08-21 23:02:02,448|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:02,448|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:02,449|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_47'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_47'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:02,482|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:02,482|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_47'}
2009-08-21 23:02:02,482|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:02,484|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:02,484|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_47'}
2009-08-21 23:02:02,487|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:02,487|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:02,487|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_47'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_48'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:02,522|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:02,522|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_47'}
2009-08-21 23:02:02,522|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:02,525|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:02,525|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_47'}
2009-08-21 23:02:02,526|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:02,526|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:02,527|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_48'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_48'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:02,567|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:02,567|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_48'}
2009-08-21 23:02:02,567|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:02,569|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:02,570|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_48'}
2009-08-21 23:02:02,571|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:02,571|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:02,572|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_48'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_48'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:02,606|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:02,606|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_48'}
2009-08-21 23:02:02,607|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:02,608|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:02,609|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_48'}
2009-08-21 23:02:02,610|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:02,611|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:02,611|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_48'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_49'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:02,647|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:02,647|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_48'}
2009-08-21 23:02:02,647|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:02,649|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:02,650|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_48'}
2009-08-21 23:02:02,652|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:02,652|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:02,652|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_49'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_49'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:02,686|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:02,686|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_49'}
2009-08-21 23:02:02,686|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:02,690|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:02,690|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello thread1_49'}
2009-08-21 23:02:02,692|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:02,692|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:02,693|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_49'}, 'routing_key': u'testthreadedclient_client_routing_key'}, {'result_message': {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_49'}, 'routing_key': u'testthreadedclient_client_routing_key'}]
2009-08-21 23:02:02,730|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:02,731|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_49'}
2009-08-21 23:02:02,731|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:02,733|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:02,734|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 1, 'result': u'Hello thread2_49'}
2009-08-21 23:02:02,773|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:02,774|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_49'}
2009-08-21 23:02:02,774|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:02,776|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:02,776|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 2, 'result': u'Hello thread3_49'}
2009-08-21 23:02:02,813|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:02,859|qam.qam_server|DEBUG|qam_server.py|__init__| #64: Init QAMServer
2009-08-21 23:02:02,946|qam.qam_server|DEBUG|qam_server.py|register_function| #109: should register method hello with name hello 
2009-08-21 23:02:02,947|qam.qam_server|DEBUG|qam_server.py|register_function| #111: register method with name hello
2009-08-21 23:02:02,947|qam.qam_server|DEBUG|qam_server.py|register_function| #109: should register method adder_function with name add 
2009-08-21 23:02:02,948|qam.qam_server|DEBUG|qam_server.py|register_function| #111: register method with name add
2009-08-21 23:02:02,948|qam.qam_server|DEBUG|qam_server.py|register_function| #109: should register method excp_method with name None 
2009-08-21 23:02:02,948|qam.qam_server|DEBUG|qam_server.py|register_function| #114: register method with name excp_method
2009-08-21 23:02:02,948|qam.qam_server|DEBUG|qam_server.py|register_function| #109: should register method object_method with name None 
2009-08-21 23:02:02,949|qam.qam_server|DEBUG|qam_server.py|register_function| #114: register method with name object_method
2009-08-21 23:02:02,950|qam.qam_server|DEBUG|qam_server.py|register_function| #109: should register method callback_test_method with name None 
2009-08-21 23:02:02,950|qam.qam_server|DEBUG|qam_server.py|register_function| #114: register method with name callback_test_method
2009-08-21 23:02:02,950|qam.qam_server|DEBUG|qam_server.py|register_function| #109: should register method callback_exception with name None 
2009-08-21 23:02:02,950|qam.qam_server|DEBUG|qam_server.py|register_function| #114: register method with name callback_exception
2009-08-21 23:02:03,074|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:03,075|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': 3}, 'routing_key': u'testexception _client_routing_key'}]
2009-08-21 23:02:03,075|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': 3}
2009-08-21 23:02:03,075|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:03,077|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:03,077|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': 3}
2009-08-21 23:02:03,117|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:03,164|qam.qam_server|DEBUG|qam_server.py|__init__| #64: Init QAMServer
2009-08-21 23:02:03,250|qam.qam_server|DEBUG|qam_server.py|register_function| #109: should register method hello with name hello 
2009-08-21 23:02:03,251|qam.qam_server|DEBUG|qam_server.py|register_function| #111: register method with name hello
2009-08-21 23:02:03,251|qam.qam_server|DEBUG|qam_server.py|register_function| #109: should register method adder_function with name add 
2009-08-21 23:02:03,251|qam.qam_server|DEBUG|qam_server.py|register_function| #111: register method with name add
2009-08-21 23:02:03,252|qam.qam_server|DEBUG|qam_server.py|register_function| #109: should register method excp_method with name None 
2009-08-21 23:02:03,253|qam.qam_server|DEBUG|qam_server.py|register_function| #114: register method with name excp_method
2009-08-21 23:02:03,254|qam.qam_server|DEBUG|qam_server.py|register_function| #109: should register method object_method with name None 
2009-08-21 23:02:03,254|qam.qam_server|DEBUG|qam_server.py|register_function| #114: register method with name object_method
2009-08-21 23:02:03,254|qam.qam_server|DEBUG|qam_server.py|register_function| #109: should register method callback_test_method with name None 
2009-08-21 23:02:03,255|qam.qam_server|DEBUG|qam_server.py|register_function| #114: register method with name callback_test_method
2009-08-21 23:02:03,255|qam.qam_server|DEBUG|qam_server.py|register_function| #109: should register method callback_exception with name None 
2009-08-21 23:02:03,255|qam.qam_server|DEBUG|qam_server.py|register_function| #114: register method with name callback_exception
2009-08-21 23:02:03,383|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:03,384|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:03,384|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello Teststring'}, 'routing_key': u'testqamclient2_client_routing_key'}]
2009-08-21 23:02:03,384|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello Teststring'}
2009-08-21 23:02:03,384|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:03,385|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:03,386|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Hello Teststring'}
2009-08-21 23:02:03,421|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
2009-08-21 23:02:03,466|qam.qam_server|DEBUG|qam_server.py|__init__| #64: Init QAMServer
2009-08-21 23:02:03,551|qam.qam_server|DEBUG|qam_server.py|register_function| #109: should register method hello with name hello 
2009-08-21 23:02:03,551|qam.qam_server|DEBUG|qam_server.py|register_function| #111: register method with name hello
2009-08-21 23:02:03,552|qam.qam_server|DEBUG|qam_server.py|register_function| #109: should register method adder_function with name add 
2009-08-21 23:02:03,552|qam.qam_server|DEBUG|qam_server.py|register_function| #111: register method with name add
2009-08-21 23:02:03,552|qam.qam_server|DEBUG|qam_server.py|register_function| #109: should register method excp_method with name None 
2009-08-21 23:02:03,553|qam.qam_server|DEBUG|qam_server.py|register_function| #114: register method with name excp_method
2009-08-21 23:02:03,553|qam.qam_server|DEBUG|qam_server.py|register_function| #109: should register method object_method with name None 
2009-08-21 23:02:03,554|qam.qam_server|DEBUG|qam_server.py|register_function| #114: register method with name object_method
2009-08-21 23:02:03,554|qam.qam_server|DEBUG|qam_server.py|register_function| #109: should register method callback_test_method with name None 
2009-08-21 23:02:03,554|qam.qam_server|DEBUG|qam_server.py|register_function| #114: register method with name callback_test_method
2009-08-21 23:02:03,554|qam.qam_server|DEBUG|qam_server.py|register_function| #109: should register method callback_exception with name None 
2009-08-21 23:02:03,555|qam.qam_server|DEBUG|qam_server.py|register_function| #114: register method with name callback_exception
2009-08-21 23:02:03,679|qam.qam_server|DEBUG|qam_server.py|run| #205: Start Run
2009-08-21 23:02:03,679|qam.qam_server|DEBUG|qam_server.py|run| #216: in Method Call
2009-08-21 23:02:03,679|qam.qam_server|DEBUG|qam_server.py|run| #254: Method Queue: [{'result_message': {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Callback test result: test'}, 'routing_key': u'testexception_client_routing_key'}]
2009-08-21 23:02:03,680|qam.qam_server|DEBUG|qam_server.py|run| #306: popped message from queue: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Callback test result: test'}
2009-08-21 23:02:03,680|qam.qam_server|DEBUG|qam_server.py|run| #308: create Publisher
2009-08-21 23:02:03,687|qam.qam_server|DEBUG|qam_server.py|run| #312: created Publisher
2009-08-21 23:02:03,687|qam.qam_server|DEBUG|qam_server.py|run| #314: sent message: {'exception': False, 'internal_exception': -1, 'id': 0, 'result': u'Callback test result: test'}
2009-08-21 23:02:03,729|qam.qam_server|DEBUG|qam_server.py|run| #316: publisher closed
