"""
   >>> import grokcore.component.tests.directive.argumenterror_fixture
   Traceback (most recent call last):
     ...
   TypeError: grok.name takes exactly 1 argument (3 given)
"""
